### ISSUE TITLE
Not compatible with Django 1.9? :(

### ISSUE THREAD

**Issue by koleror** [team23/django_cloneable#6]
Hi,
I'm trying to migrate my project to Django 1.9, but your module seems to cause an error :(
Here's my traceback:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "<site-packages>/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "<site-packages>/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "<site-packages>/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<site-packages>/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "<site-packages>/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "<project root>/my_app/models.py", line 16, in <module>
    from django_cloneable import CloneableMixin
  File "<site-packages>/django_cloneable/__init__.py", line 1, in <module>
    from .models import CloneableMixin  # noqa
  File "<site-packages>/django_cloneable/models.py", line 161, in <module>
    class CloneableMixin(models.Model):
  File "<site-packages>/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "<site-packages>/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "<site-packages>/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

I also tried to add the app in `INSTALLED_APPS`, but it fails with the following traceback:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "<site-packages>/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "<site-packages>/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "<site-packages>/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<site-packages>/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "<site-packages>/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "<site-packages>/django_cloneable/__init__.py", line 1, in <module>
    from .models import CloneableMixin  # noqa
  File "<site-packages>/django_cloneable/models.py", line 161, in <module>
    class CloneableMixin(models.Model):
  File "<site-packages>/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "<site-packages>/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "<site-packages>/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Any clue?

**Comment by ddanier** [comment]
Please try installing the current version from git (master)

**Comment by ddanier** [comment]
Did that work?

**Comment by koleror** [comment]
Hi! Sorry for the delay, no it did not work but I found what the issue was, and it as in my code.
Thanks for your help!
